package de.q60.mps.shadowmodels.runtime.model.persistent;

/*Generated by MPS */


public interface IReadTransaction extends ITransaction {
  void registerMissingNode(IMissingNode missingNode);
  Iterable<IMissingNode> getMissingNodes();
}
