FROM webmps-mps
WORKDIR /usr/webmps-ui
EXPOSE 33333
ADD build/de.q60.mps.web/build/artifacts/de.q60.mps.web/de.q60.mps.web.zip /usr/webmps-ui/mps/plugins/
COPY run-ui-server.sh /usr/webmps-ui
COPY ui-server/build/libs/ui-server-1.0-SNAPSHOT.jar /usr/webmps-ui/ui-server.jar
COPY healthcheck-ui.sh /usr/webmps-ui/
HEALTHCHECK CMD /usr/webmps-ui/healthcheck.sh
CMD ["./run-ui-server.sh"]