FROM modelix/projector-mps:2020.3.5

COPY install-plugins.sh /
COPY build/branding.zip /projector/ide/lib/branding.jar

COPY artifacts/de.itemis.mps.extensions/ /mps-plugins/MPS-extensions
COPY build/org.modelix/build/artifacts/org.modelix/plugins/ /mps-plugins/modelix

USER root
RUN /install-plugins.sh /projector/ide/plugins/
COPY projector-user-home /home/projector-user
RUN chown -R projector-user:projector-user /home/projector-user
USER projector-user
