FROM openjdk:11

RUN apt update && apt install -y maven git ant

WORKDIR /workspace-job/
COPY workspace-job/build/install/workspace-job /workspace-job/

COPY artifacts/mps /mps
COPY headless-runner/build/libs /headless-runner

COPY artifacts/de.itemis.mps.extensions /languages/mps-extensions
COPY build/org.modelix/build/artifacts/org.modelix /languages/modelix

CMD ["/workspace-job/bin/workspace-job", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5071", "-Dmps.home=/mps", "-XX:MaxRAMPercentage=75"]
