FROM modelix/projector-mps:2020.3.5

COPY install-plugins.sh /
COPY build/branding.zip /projector/ide/lib/branding.jar

COPY artifacts/de.itemis.mps.extensions/ /mps-plugins/MPS-extensions
COPY build/org.modelix/build/artifacts/org.modelix/plugins/ /mps-plugins/modelix

USER root
RUN /install-plugins.sh /projector/ide/plugins/
USER projector-user

RUN mkdir -p /home/projector-user/.local/share/JetBrains/consentOptions/ && echo "rsch.send.usage.stat:1.1:0:1636142999385" > /home/projector-user/.local/share/JetBrains/consentOptions/accepted
