ARG MPS_VERSION
FROM modelix/projector-mps:$MPS_VERSION

USER root
COPY install-plugins.sh /
COPY build/branding.zip /projector/ide/lib/branding.jar

RUN apt-get update \
    && apt-get install unzip -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/apt \
    && echo "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5071" >> /projector/ide/bin/mps64.vmoptions \
    && sed -i.bak '/-Xmx/d' /projector/ide/bin/mps64.vmoptions \
    && echo "-XX:MaxRAMPercentage=85" >> /projector/ide/bin/mps64.vmoptions \
    && mkdir -p /mps-plugins \
    && mkdir -p /mps-languages \
    && chown -R projector-user:projector-user /home/projector-user \
    && chown -R projector-user:projector-user /mps-plugins \
    && chown -R projector-user:projector-user /mps-languages \
    && chown -R projector-user:projector-user /projector/ide/

USER projector-user
