package de.q60.webmps.server;

/*Generated by MPS */


import java.net.InetAddress;
import java.net.InetSocketAddress;

public class Main {
    public static void main(String[] args) {
        System.out.println("Server process started");

        System.out.println("Waiting ");

        try {
            String portStr = System.getenv("PORT");
            InetSocketAddress bindTo = new InetSocketAddress(InetAddress.getByName("0.0.0.0"),
                    portStr == null ? 28101 : Integer.parseInt(portStr));
            ModelServer server = new ModelServer(bindTo, new IgniteStoreClient());
            server.start();
            System.out.println("Server started");
        } catch (Exception ex) {
            System.out.println("Server failed: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
}
