package de.q60.webmps.server;

/*Generated by MPS */

import org.eclipse.jetty.websocket.api.RemoteEndpoint;
import org.json.JSONObject;

public interface MessageHandler {
  void handle(RemoteEndpoint conn, JSONObject message);
}
