package de.q60.webmps.server;

/*Generated by MPS */


public interface IKeyValueStore {
  String get(String key);
  void put(String key, String value);

  void listen(final String key, final IKeyListener listener);
}
