package de.q60.webmps.server;

/*Generated by MPS */

import org.java_websocket.WebSocket;
import org.json.JSONObject;

public interface MessageHandler {
  void handle(WebSocket conn, JSONObject message);
}
