package de.q60.webmps.server;

/*Generated by MPS */

import org.java_websocket.WebSocket;

import java.util.HashSet;
import java.util.Set;

public class Session {

  private WebSocket connection;
  private Set<String> subscribedKeys = new HashSet<String>();

  public Session(WebSocket conn) {
    connection = conn;
  }

  public void dispose() {
  }

  public WebSocket getConnection() {
    return this.connection;
  }

  public boolean isSubscribed(String key) {
    return subscribedKeys.contains(key);
  }

  public void subscribe(String key) {
    subscribedKeys.add(key);
  }

  public void unsubscribe(String key) {
    subscribedKeys.remove(key);
  }
}
