{{ if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ include "modelix.fullname" . }}-letsencrypt-production"
spec:
  acme:
    privateKeySecretRef:
      name: "{{ include "modelix.fullname" . }}-letsencrypt-production"
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
{{ end }}
