{{- if and (not .Values.ingress.certSecret) (not .Values.certmanager.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "modelix.fullname" . }}-tls-secret"
type: kubernetes.io/tls
data:
  {{ if .Values.ingress.tls.crt }}
  tls.crt: {{ .Values.ingress.tls.crt }}
  tls.key: {{ .Values.ingress.tls.key }}
  {{ else }}
  {{- $altNames := list .Values.ingress.hostname -}}
  {{- $ca := genCA "modelix-ca" 365 -}}
  {{- $cert := genSignedCert ( include "modelix.fullname" . ) nil $altNames 365 $ca -}}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  {{- end }}
{{ end }}
