package de.q60.mps.shadowmodels.runtime.model;

/*Generated by MPS */

import de.q60.mps.incremental.util.ContextValue;

public interface INodeResolveContext {
  ContextValue<INodeResolveContext> CONTEXT_VALUE = new ContextValue<INodeResolveContext>();
  INode resolve(INodeReference ref);
}
